trigger:
- master

pool:
  name: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: self
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'azuredevops'
        repository: 'gavriel8080/repro'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
